#!/usr/bin/env npx tsx
/**
 * scripts/export-content-seed.ts
 *
 * Converts courseData.ts bundle into a Supabase seed SQL file:
 *   supabase/seed.sql
 *
 * Usage:
 *   npx tsx scripts/export-content-seed.ts
 *
 * The script inserts into:
 *   courses → course_modules → module_blocks (slides, practice, quiz)
 *
 * Idempotent: uses ON CONFLICT DO NOTHING on the course slug,
 * and deletes+reinserts modules for a clean re-run.
 */

import { writeFileSync } from 'fs';
import { courseModules } from '../src/content/courseData';
import type { CourseModule, Slide, PracticeTask, QuizQuestion } from '../src/types';

const COURSE_SLUG = 'vibe-coding-basics';
const COURSE_TITLE = 'Vibe-Coding: от идеи до релиза';

function sq(value: unknown): string {
  if (value === null || value === undefined) return 'NULL';
  if (typeof value === 'number' || typeof value === 'boolean') return String(value);
  // Escape single quotes for SQL string literals
  return `'${JSON.stringify(value).replace(/'/g, "''")}'`;
}

function sqlJsonb(value: unknown): string {
  return `'${JSON.stringify(value).replace(/'/g, "''")}'::jsonb`;
}

const lines: string[] = [];

lines.push('-- Auto-generated by scripts/export-content-seed.ts');
lines.push('-- Run: npx tsx scripts/export-content-seed.ts');
lines.push('-- Then: supabase db push (or paste into SQL editor)');
lines.push('');
lines.push('-- ── Course ──────────────────────────────────────────────────────');
lines.push(`INSERT INTO courses (slug, title, status, created_at)`);
lines.push(`VALUES (${sq(COURSE_SLUG)}, ${sq(COURSE_TITLE)}, 'published', now())`);
lines.push(`ON CONFLICT (slug) DO UPDATE SET title = EXCLUDED.title, status = 'published';`);
lines.push('');
lines.push(`-- Capture course id into a temp variable`);
lines.push(`DO $$`);
lines.push(`DECLARE`);
lines.push(`  v_course_id uuid;`);
lines.push(`  v_module_id uuid;`);
lines.push(`BEGIN`);
lines.push(`  SELECT id INTO v_course_id FROM courses WHERE slug = ${sq(COURSE_SLUG)};`);
lines.push('');
lines.push(`  -- ── Clean existing modules for idempotency ──────────────────`);
lines.push(`  DELETE FROM module_blocks WHERE module_id IN (`);
lines.push(`    SELECT id FROM course_modules WHERE course_id = v_course_id`);
lines.push(`  );`);
lines.push(`  DELETE FROM course_modules WHERE course_id = v_course_id;`);
lines.push('');

(courseModules as CourseModule[]).forEach((mod, modIdx) => {
  const modSlug = `week-${mod.id}`;
  lines.push(`  -- ── Week ${mod.id}: ${mod.title} ─────────────────────────────`);
  lines.push(`  INSERT INTO course_modules`);
  lines.push(`    (course_id, slug, position, title, duration, short_description, full_description, concept)`);
  lines.push(`  VALUES (`);
  lines.push(`    v_course_id,`);
  lines.push(`    ${sq(modSlug)},`);
  lines.push(`    ${mod.id},`);
  lines.push(`    ${sq(mod.title)},`);
  lines.push(`    ${sq(mod.duration)},`);
  lines.push(`    ${sq(mod.shortDescription)},`);
  lines.push(`    ${sq(mod.fullDescription)},`);
  lines.push(`    ${sq(mod.concept)}`);
  lines.push(`  ) RETURNING id INTO v_module_id;`);
  lines.push('');

  // Slides
  (mod.slides as Slide[]).forEach((slide, i) => {
    lines.push(`  INSERT INTO module_blocks (module_id, kind, position, payload)`);
    lines.push(`  VALUES (v_module_id, 'slide', ${i + 1}, ${sqlJsonb(slide)});`);
  });
  lines.push('');

  // Practice
  if (mod.practice) {
    const practice = mod.practice as PracticeTask;
    lines.push(`  INSERT INTO module_blocks (module_id, kind, position, payload)`);
    lines.push(`  VALUES (v_module_id, 'practice', 1, ${sqlJsonb(practice)});`);
    lines.push('');
  }

  // Quiz
  (mod.quiz as QuizQuestion[]).forEach((q, i) => {
    lines.push(`  INSERT INTO module_blocks (module_id, kind, position, payload)`);
    lines.push(`  VALUES (v_module_id, 'quiz', ${i + 1}, ${sqlJsonb(q)});`);
  });
  lines.push('');

  void modIdx; // suppress unused var warning
});

lines.push(`END $$;`);
lines.push('');
lines.push(`-- Verify`);
lines.push(`SELECT cm.position, cm.title, count(mb.id) AS blocks`);
lines.push(`FROM course_modules cm`);
lines.push(`LEFT JOIN module_blocks mb ON mb.module_id = cm.id`);
lines.push(`JOIN courses c ON c.id = cm.course_id`);
lines.push(`WHERE c.slug = ${sq(COURSE_SLUG)}`);
lines.push(`GROUP BY cm.position, cm.title`);
lines.push(`ORDER BY cm.position;`);

const output = lines.join('\n');
const outPath = 'supabase/seed.sql';
writeFileSync(outPath, output, 'utf8');

console.log(`✓ Seed SQL written to ${outPath}`);
console.log(`  Modules: ${courseModules.length}`);
console.log(`  Total blocks: ${courseModules.reduce((acc, m) => acc + m.slides.length + (m.practice ? 1 : 0) + m.quiz.length, 0)}`);
