-- ============================================================
-- Centras CodeAI — Platform Core Schema (Release 1.0)
-- Контент курсов, прогресс, сабмишены, события тура, AI-учёт.
-- Применение: supabase db push
-- ============================================================

-- ---------- Вспомогательная функция ролей (без рекурсии RLS) ----------
create or replace function public.is_staff()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role in ('teacher', 'admin')
  );
$$;

-- ---------- Когорты ----------
create table if not exists public.cohorts (
  id bigint generated by default as identity primary key,
  name text not null,
  active_week int not null default 1,
  created_at timestamptz not null default now()
);

-- Drip-расписание: какая неделя открывается когда (опционально, поверх active_week)
create table if not exists public.cohort_schedule (
  id bigint generated by default as identity primary key,
  cohort_id bigint not null references public.cohorts(id) on delete cascade,
  week_id int not null,
  opens_at timestamptz not null,
  unique (cohort_id, week_id)
);

-- ---------- Профили ----------
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  name text not null default '',
  role text not null default 'student' check (role in ('student', 'teacher', 'admin')),
  cohort_id bigint references public.cohorts(id),
  created_at timestamptz not null default now()
);

-- Автосоздание профиля при регистрации
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, email, name, role, cohort_id)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data ->> 'name', split_part(new.email, '@', 1)),
    case
      when coalesce(new.raw_user_meta_data ->> 'role', 'student') in ('student', 'teacher')
        then coalesce(new.raw_user_meta_data ->> 'role', 'student')
      else 'student' -- admin назначается только вручную через SQL
    end,
    1
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- ---------- Контент: курсы → модули → блоки ----------
create table if not exists public.courses (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  title text not null,
  description text not null default '',
  status text not null default 'draft' check (status in ('draft', 'published', 'archived')),
  position int not null default 0,
  version int not null default 1,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.course_modules (
  id uuid primary key default gen_random_uuid(),
  course_id uuid not null references public.courses(id) on delete cascade,
  position int not null,
  title text not null,
  duration text not null default '',
  short_description text not null default '',
  full_description text not null default '',
  concept text not null default '',
  unique (course_id, position)
);

-- Блок = слайд | практика | вопрос квиза. payload повторяет типы клиента (types.ts).
create table if not exists public.module_blocks (
  id uuid primary key default gen_random_uuid(),
  module_id uuid not null references public.course_modules(id) on delete cascade,
  kind text not null check (kind in ('slide', 'practice', 'quiz')),
  position int not null,
  payload jsonb not null,
  unique (module_id, kind, position)
);

create index if not exists idx_module_blocks_module on public.module_blocks(module_id);

-- ---------- Записи на курс ----------
create table if not exists public.enrollments (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  course_id uuid not null references public.courses(id) on delete cascade,
  cohort_id bigint references public.cohorts(id),
  created_at timestamptz not null default now(),
  unique (user_id, course_id)
);

-- ---------- Прогресс (заменяет localStorage) ----------
create table if not exists public.progress (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  course_slug text not null default 'vibe-coding-basics',
  week_id int not null,
  status text not null default 'in_progress' check (status in ('in_progress', 'completed')),
  quiz_score int,
  checklist jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  unique (user_id, course_slug, week_id)
);

-- ---------- Сабмишены (заменяет homeworks; вердикт ставит только сервер) ----------
create table if not exists public.submissions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  course_slug text not null default 'vibe-coding-basics',
  week_id int not null,
  kind text not null check (kind in ('code', 'prompt')),
  payload jsonb not null,              -- {html, css, js} | {prompt}
  static_results jsonb,                -- результаты статических проверок
  functional_results jsonb,            -- результаты функциональных тестов (из песочницы)
  rubric_results jsonb,                -- по-критерийная рубрика от LLM
  score int not null default 0,
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
  review_text text not null default '',
  created_at timestamptz not null default now()
);

create index if not exists idx_submissions_user on public.submissions(user_id);
create index if not exists idx_submissions_week on public.submissions(course_slug, week_id);

-- ---------- Аналитика тура ----------
create table if not exists public.tour_events (
  id bigint generated by default as identity primary key,
  anon_id text,
  user_id uuid references public.profiles(id) on delete set null,
  step text not null,
  event text not null,
  meta jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_tour_events_step on public.tour_events(step, event);

-- ---------- Учёт вызовов LLM и кэш ----------
create table if not exists public.ai_calls (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete set null,
  anon_id text,
  task text not null,
  model text not null,
  cached boolean not null default false,
  input_chars int not null default 0,
  output_chars int not null default 0,
  duration_ms int not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists idx_ai_calls_user_time on public.ai_calls(user_id, created_at);
create index if not exists idx_ai_calls_anon_time on public.ai_calls(anon_id, created_at);

create table if not exists public.ai_cache (
  hash text primary key,
  task text not null,
  response jsonb not null,
  created_at timestamptz not null default now()
);

-- ============================================================
-- RLS
-- ============================================================
alter table public.cohorts enable row level security;
alter table public.cohort_schedule enable row level security;
alter table public.profiles enable row level security;
alter table public.courses enable row level security;
alter table public.course_modules enable row level security;
alter table public.module_blocks enable row level security;
alter table public.enrollments enable row level security;
alter table public.progress enable row level security;
alter table public.submissions enable row level security;
alter table public.tour_events enable row level security;
alter table public.ai_calls enable row level security;
alter table public.ai_cache enable row level security;

-- Профили: свой — читать/обновлять; staff видит всех
drop policy if exists "profiles_select_own" on public.profiles;
create policy "profiles_select_own" on public.profiles
  for select using (id = auth.uid() or public.is_staff());

drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_update_own" on public.profiles
  for update using (id = auth.uid());

-- Когорты: читают все аутентифицированные; правит staff
drop policy if exists "cohorts_select_auth" on public.cohorts;
create policy "cohorts_select_auth" on public.cohorts
  for select using (auth.role() = 'authenticated');

drop policy if exists "cohorts_update_staff" on public.cohorts;
create policy "cohorts_update_staff" on public.cohorts
  for update using (public.is_staff());

drop policy if exists "cohort_schedule_select_auth" on public.cohort_schedule;
create policy "cohort_schedule_select_auth" on public.cohort_schedule
  for select using (auth.role() = 'authenticated');

drop policy if exists "cohort_schedule_write_staff" on public.cohort_schedule;
create policy "cohort_schedule_write_staff" on public.cohort_schedule
  for all using (public.is_staff());

-- Контент: published читают все (включая анонимов — нужен лендингу и туру);
-- черновики и запись — только staff
drop policy if exists "courses_select_published" on public.courses;
create policy "courses_select_published" on public.courses
  for select using (status = 'published' or public.is_staff());

drop policy if exists "courses_write_staff" on public.courses;
create policy "courses_write_staff" on public.courses
  for all using (public.is_staff());

drop policy if exists "modules_select_published" on public.course_modules;
create policy "modules_select_published" on public.course_modules
  for select using (
    exists (select 1 from public.courses c where c.id = course_id and (c.status = 'published' or public.is_staff()))
  );

drop policy if exists "modules_write_staff" on public.course_modules;
create policy "modules_write_staff" on public.course_modules
  for all using (public.is_staff());

drop policy if exists "blocks_select_published" on public.module_blocks;
create policy "blocks_select_published" on public.module_blocks
  for select using (
    exists (
      select 1 from public.course_modules m
      join public.courses c on c.id = m.course_id
      where m.id = module_id and (c.status = 'published' or public.is_staff())
    )
  );

drop policy if exists "blocks_write_staff" on public.module_blocks;
create policy "blocks_write_staff" on public.module_blocks
  for all using (public.is_staff());

-- Записи на курс: свои
drop policy if exists "enrollments_own" on public.enrollments;
create policy "enrollments_own" on public.enrollments
  for all using (user_id = auth.uid() or public.is_staff());

-- Прогресс: студент управляет своим, staff читает всё
drop policy if exists "progress_select" on public.progress;
create policy "progress_select" on public.progress
  for select using (user_id = auth.uid() or public.is_staff());

drop policy if exists "progress_insert_own" on public.progress;
create policy "progress_insert_own" on public.progress
  for insert with check (user_id = auth.uid());

drop policy if exists "progress_update_own" on public.progress;
create policy "progress_update_own" on public.progress
  for update using (user_id = auth.uid());

-- Сабмишены: читать свои (staff — все). INSERT-политики нет:
-- запись делает только edge-функция ai-gateway (service role, минуя RLS).
-- Так студент не может подделать score/status из консоли браузера.
drop policy if exists "submissions_select" on public.submissions;
create policy "submissions_select" on public.submissions
  for select using (user_id = auth.uid() or public.is_staff());

-- События тура: писать могут все (включая анонимов), читать — staff
drop policy if exists "tour_events_insert_any" on public.tour_events;
create policy "tour_events_insert_any" on public.tour_events
  for insert with check (true);

drop policy if exists "tour_events_select_staff" on public.tour_events;
create policy "tour_events_select_staff" on public.tour_events
  for select using (public.is_staff());

-- ai_calls / ai_cache: только service role (политик нет => deny всем остальным),
-- staff может смотреть расход
drop policy if exists "ai_calls_select_staff" on public.ai_calls;
create policy "ai_calls_select_staff" on public.ai_calls
  for select using (public.is_staff());

-- ============================================================
-- Seed: базовая когорта
-- ============================================================
insert into public.cohorts (id, name, active_week)
values (1, 'Весенняя когорта 2026', 1)
on conflict (id) do nothing;
