-- SQL Migration: Initialize Course Database Schema

-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- 1. Create Cohorts Table
create table if not exists public.cohorts (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    name text not null,
    active_week integer default 1 not null
);

-- Enable RLS on Cohorts
alter table public.cohorts enable row level security;

-- Policies for Cohorts
create policy "Allow public read access to cohorts" on public.cohorts
    for select using (true);

create policy "Allow admin write access to cohorts" on public.cohorts
    for all using (true); -- Simplified for educational setup

-- 2. Create User Profiles Table
create table if not exists public.profiles (
    id uuid references auth.users on delete cascade primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    email text not null,
    role text default 'student'::text check (role in ('student', 'teacher')) not null,
    name text,
    cohort_id bigint references public.cohorts(id)
);

-- Enable RLS on Profiles
alter table public.profiles enable row level security;

-- Policies for Profiles
create policy "Allow users to read all profiles" on public.profiles
    for select using (true);

create policy "Allow users to update own profile" on public.profiles
    for update using (auth.uid() = id);

create policy "Allow system/admins to insert profiles" on public.profiles
    for insert with check (true);

-- 3. Create Homework Submissions Table
create table if not exists public.homeworks (
    id uuid default gen_random_uuid() primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    student_id uuid references public.profiles(id) on delete cascade not null,
    week_id integer not null,
    code_html text default ''::text not null,
    code_css text default ''::text not null,
    code_js text default ''::text not null,
    score integer,
    review_text text,
    status text default 'pending'::text check (status in ('pending', 'approved', 'rejected')) not null,
    submitted_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS on Homeworks
alter table public.homeworks enable row level security;

-- Policies for Homeworks
create policy "Allow students to view own homeworks" on public.homeworks
    for select using (auth.uid() = student_id);

create policy "Allow teachers to view all homeworks" on public.homeworks
    for select using (
        exists (
            select 1 from public.profiles
            where profiles.id = auth.uid() and profiles.role = 'teacher'
        )
    );

create policy "Allow students to insert own homeworks" on public.homeworks
    for insert with check (auth.uid() = student_id);

create policy "Allow teachers/functions to update homeworks" on public.homeworks
    for update using (
        exists (
            select 1 from public.profiles
            where profiles.id = auth.uid() and profiles.role = 'teacher'
        )
    );

-- Helper functions
-- Auto-create profile on auth signup
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, email, name, role)
  values (new.id, new.email, new.raw_user_meta_data->>'name', coalesce(new.raw_user_meta_data->>'role', 'student'));
  return new;
end;
$$ language plpgsql security definer;

-- Trigger to hook on auth.users
create or replace trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
